### PR TITLE
Working with multiple channel

### PR DESCRIPTION
**Pull request by hugohil**
This a work in progress PR to allow per-channel extraction.

For now, I have made some "instanciable" `meyda` object to get things to work quick and be able to test. I'll update this to use a proper `class` for the whole Meyda instance later, when we'll agree on the API we want.

### CODE REVIEW

**Comment by jakubfiala** [comment]
@hugohil please let us know when this PR is ready to review/discuss with others 😉

**Comment by hugohil** [comment]
Hi,
I'm sorry for the delay, I got caught by other things...
I took some time to look this morning but still couldn't figure out why the `inputBuffer` of the `scriptProcessingNode` that is connected to my `channelSplitterNode` returns every data into the first channel. I did initialized the spn with the correct channel number.
I need to take another look I guess, and to dive deeper into Web Audio specs.

**Comment by hugohil** [comment]
I'm closing this PR and starting over from master since a lot of changes occured and it's been a long time I have not been working on on it.
I'll keep you posted.

**Comment by jakubfiala** [comment]
@hugohil sounds fair, thanks for working on this!

**Pull request closed without merging**
