### PR TITLE
Add support for node 18

### LINKED ISSUE #1470: Node 18 support
Hi! I see that node 18 is not suported in `package.json`. Is this a concious decision, maybe some breaking change that needs fixing?

Or could this just be added and probably work fine?

### PR DESCRIPTION
**Pull request by remlse**
closes #1470 

I've used the same commit message style as the dependabot commits. Maybe this is not desired and something else should be used so it can be distinguished better? I'll be happy to change it.

I've never personally worked with npm (only yarn and pnpm). `npm install` made some changes to the lock file, but a quick search tells me this is normal for npm? Otherwise I would try to not change the lock file unintentionally.

### CODE REVIEW

**Comment by 2xAA** [comment]
Thanks @remlse. Adding myself and @hughrawlinson as reviewers as I've recently also required node 18 support.
Hope to get this merged soon :)

**Review by 2xAA — APPROVED** [review]

**Comment by 2xAA** [comment]
Ran the test suite locally on Node 18.13.0 - all good!

```bash
Test Suites: 24 passed, 24 total
Tests:       112 passed, 112 total
Snapshots:   0 total
Time:        3.458 s
Ran all test suites.
```

**Comment by remlse** [comment]
@hughrawlinson pinging in case it was forgotten

**Comment by AvantGov** [comment]
i am going to hop in here because I have been experiencing the same failure that spawned this when trying to install packages for a project running hydra-synth (utilizing meyda) and would really like to finish working on it. @hughrawlinson could you approve this merge and follow up with the comment about the failing build if you have the time?

**Comment by hughrawlinson** [comment]
Sorry for the delay on this! Just published 5.6.0 which adds support for node 18 and 19.

**Comment by AvantGov** [comment]
Thanks so much, @hughrawlinson! And @remlse for getting the ball rolling on this initially. Appreciate y'all :,-)

**Pull request merged**
