### PR TITLE
chore(node): Added 16

### PR DESCRIPTION
**Pull request by TimPietrusky**
## Context
In order to use meyda on a Mac M1, I need to use Node 16.x as this is the only supported Node on that platform. 

## Info
* Makes meyda work with Node 16
* All tests are passing using Node 16.2.0

### CODE REVIEW

**Comment by hughrawlinson** [comment]
Hi @TimPietrusky! This PR is failing because the commit message isn't formatted with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/). If you have time to amend the message, go for it and I'll merge ASAP. Otherwise, when I have time I'd be happy to do the upgrade so you don't have to. Thanks for testing it out!

**Comment by hughrawlinson** [comment]
Also, in this commit could you add node 16 to our travis.yml so that tests run in CI?

**Comment by hughrawlinson** [comment]
To clarify, the issue is the capital S in support - `fix(node): support for 16` is valid. I'm sorry for the trouble, semantic release would be a lot better if it didn't have so many quirks.

**Comment by TimPietrusky** [comment]
@hughrawlinson of course no problem. I was checking out the contributor guidelines but couldn't figure out that the conventions enforces to have the description in lowercase -> fixed. 

I also added Node 16 to travis.yml as requested.

**Comment by hughrawlinson** [comment]
Yep, the docs aren't clear on that. I've added some clarity in #827, hopefully that'll help future contributors!

This is great, thank you for the PR! meyda@5.1.5 should be published by CI in a few minutes and will contain M1 support. Great stuff!

**Review by hughrawlinson — APPROVED** [review]

**Comment by hughrawlinson** [comment]
:partying_face: https://unpkg.com/meyda@5.1.5/dist/web/meyda.min.js

**Comment by hughrawlinson** [comment]
It looks like starting at 5.1.4 I inadvertently introduced a bug, sorry. I'll fix that tonight, and then you should have a working copy!

**Comment by TimPietrusky** [comment]
@hughrawlinson oh really? It was working for us yesterday as we tested our version inside of modV. Where exactly is the bug?

**Comment by hughrawlinson** [comment]
[We released yesterday](https://github.com/meyda/meyda/pull/828), and one of the commits had a prettier run, which switched a file to es6 exports, which means that in the current bundle you have to do `const meyda = require("meyda").default`, rather than `const meyda = require("meyda")` as documented. An issue with our UMD bundling. PR is #828, but not working yet. Will definitely fix it this evening and mark 5.1.4 and 5.1.5 as deprecated.

**Comment by hughrawlinson** [comment]
@TimPietrusky heads up, that issue is resolved in 5.1.7, just published!

**Comment by TimPietrusky** [comment]
@hughrawlinson thank you very much!

**Pull request merged**
