### PR TITLE
Per channel extraction

### PR DESCRIPTION
**Pull request by hughrawlinson**
I added some logic to warn the user when they request a channel that doesn't exist.

Hey @hugohil, I ran this locally and it works great! Thanks so much for putting the effort in to get this working. I have a few comments I hope you don't mind talking me through 😄 

The MVP way of getting a second channel will be something like: 

```js
const analyzer = Meyda.createMeydaAnalyzer({
    "audioContext": audioContext,
    "source": source,
    "bufferSize": 512,
    "featureExtractors": ["rms"],
    "inputs": 2,
    "callback": features => {
      levelRangeElement.value = features.rms;
    }
  });
  analyzer.setChannel(1);
  analyzer.start();
```

This means that the user will have to know in advance how many inputs they have even when they call `setSource`. It's also possible for a user to create a new source with fewer than the specified number of channels, which will cause an error. I wonder what you think about not taking `inputs` (and for that matter, `outputs`, which seems unused at the moment?) in the instantiation of the MeydaAnalyzer, and instead taking it from the `numberOfOutputs` property of the specified source each time the source is set? We'd need to delete and re-create the ScriptProcessorNode each time that happens, but I think it'd be worth it to simplify the API and not make the user think about input count in advance, and to eliminate the class of bugs that will stem from Meyda's 'inputs' state being out of sync with the real number of outputs that the sourceNode has?

### CODE REVIEW

**Comment by hugohil** [comment]
But wouldn't that mean analyzing all channel every time ?

For example, I usually use this with a SoundFlower virtual audio device, which has either 2 or 64 inputs, so I set up the 64 one but I actually use maybe 10 of them.

Maybe we could have both options though, one that sets up an analyzer for all inputs from the audio device, and an option for specifying which ones.

**Comment by 2xAA** [comment]
Maybe something like this?

`Meyda.setChannel(startChannel, endChannel)` and also `Meyda.setChannel([channels])`.

`Meyda.setChannel(1)` would be the same as it works now.
`Meyda.setChannel(1, 64)` would allow Meyda to analyse all 64 channels.
`Meyda.setChannel([1, 4, 45, 64])` would only analyse those channels.

**Comment by hugohil** [comment]
Yes ! That would the most versatile API.
And if you don't explicitly call the `setChannel` method, then all the device inputs are used.

**Comment by hughrawlinson** [comment]
I thought the `inputs` property of MeydaAnalyzer sets the total number of channels that the SPN can listen to, and the `channel` property sets which one Meyda's analyzing _right now_. My understanding of the code is that Meyda still only extracts features on one channel at a time, right?

So when I said that the `inputs` value shouldn't be a parameter of the MeydaAnalyzer, and should instead be picked up from the number of outputs on `source`, what I meant was that it'd be a nicer API for the user if the user didn't have to set the number of channels available to the ScriptProcessorNode on instantiation, but instead whenever a source is set the MeydaAnalyzer would delete the old ScriptProcessorNode and create a new one with the appropriate number of channels for whatever the source is.

> But wouldn't that mean analyzing all channel every time ?

No, because Meyda can still only analyze one channel at a time. Multi channel realtime extraction would be great, and we should do that too in a way that doesn't break the current API (or in a way that does and we can bundle it together with some other breaking changes and bump the major version). I really like the `setChannel` API that @2xAA described.

**Comment by hughrawlinson** [comment]
@hugohil @2xAA any thoughts on my comment?

**Comment by hugohil** [comment]
Ok, I got it, sorry, I mixed up the whole `inputs` and `channel` thing I guess...
Indeed, most of the time there's no need to set it manually, and it can even cause silly errors.
I think the best would be to have the maximum `source` outputs by default as you suggested, while still letting the possibility to set it explicitly.

**Comment by hugohil** [comment]
Also, the `setChannel` API @2xAA proposed requires the `Meyda` instance being a parent of one or multiple `MeydaAnalyzer`, whereas now it is the same thing.

**Comment by 2xAA** [comment]
I like this.

Though I'd probably change the feature per channel syntax to something more along the lines of:
```JavaScript
analyzer.setChannel([
{
 channels: 11,
 features: ['rms', 'spectralCentroid'],
}, {
 channels: [13, 14],
 features: ['chroma'],
}, {
 channels: [...Array(10).keys()].map(x => ++x), // produces an array containing Numbers 1-10
 features: ['energy'],
}]);
```

Just to keep parity with the `setChannel` function itself.

**Comment by nevosegal** [comment]
@hughrawlinson @hugohil what's the status of this ticket? Is the discussion here for future implementations or do we need to change anything in this PR?

**Comment by hughrawlinson** [comment]
Making sure this shows up in the reference docs before merging it to the v5 branch

**Comment by hughrawlinson** [comment]
489 days later @hugohil, I'm merging. Sorry this has taken so ludicrously long. I'm going to merge this to master and release a minor version bump to v4, because this isn't a breaking change.

@2xAA @jakubfiala @nevosegal I think we should do the multi-channel thing in v5. I'll make a ticket for it. I won't deploy a new version on npm right now, I'll leave it a day or two so that y'all can yell at me if you don't want it there.

**Comment by hughrawlinson** [comment]
uuuuuugh I merged to the wrong branch. fixing.

**Pull request merged**
